### ISSUE TITLE
React-toastify?

### ISSUE THREAD

**Issue by hereisadi** [E-cell-NITS/e-cell-website-22#171]
Use react-toastify to handle error notifications more properly.

**Comment by FabioSM46** [comment]
@hereisadi Hello, I would like to work on this issue. I would replace all the alerts with a toast notification. Can you assign it to me? Thank you.

**Comment by hereisadi** [comment]
> @hereisadi Hello, I would like to work on this issue. I would replace all the alerts with a toast notification. Can you assign it to me? Thank you.

Assigned. Thank you

**Comment by hereisadi** [comment]
Done.
