### ISSUE TITLE
Add a loader to the website

### ISSUE THREAD

**Issue by hereisadi** [E-cell-NITS/e-cell-website-22#182]
self explanatory

**Comment by Sky-De** [comment]
@hereisadi hi, i would like to work on this
what i want to do ?
1. adding loading class to the root div in index.html
2.css for simple loading
3. using useLayoutEffect in app.js file to remove loading class of root div element

assign this to me , thanks

**Comment by hereisadi** [comment]
Hello @Sky-De, thank you for expressing your interest in contributing to our codebase. We have a dedicated UI/UX team which plays a crucial role in confirming the design before we proceed with the implementation. So, at this stage, we are unable to accept external contributions. Your enthusiasm is greatly appreciated. Thanks.
