### ISSUE TITLE
Fix Key and Class Name Warning in Events_red Component

### ISSUE THREAD

**Issue by ManashPratimPathak** [E-cell-NITS/e-cell-website-22#80]
**When using the Events_red component, we're getting two warnings in the console that need to be fixed.**

The first warning says "Each child in a list should have a unique 'key' prop.". We need to ensure that each child element in the Events_red component has a unique key prop.

The second warning says "Invalid DOM property class. Did you mean className?". We need to update the class property to className in the Events_red component.

![key-prop-issues](https://user-images.githubusercontent.com/85903876/223783694-fa3f4066-7869-4dac-ab22-3890d72fadb9.jpg)
![event_red issues](https://user-images.githubusercontent.com/85903876/223783920-894a5602-128a-4b21-b421-11d4143993b6.jpg)

**Comment by priyajit27** [comment]
sponsors section issue1 resolved.
